# Generated by Django 4.2.5 on 2023-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emp_Data_Table",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=15)),
                ("lastname", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=15)),
                ("dsg", models.CharField(max_length=30)),
                ("salary", models.IntegerField()),
                ("city", models.CharField(default="", max_length=20, null=True)),
                ("state", models.CharField(default="", max_length=20, null=True)),
            ],
        ),
    ]
